//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoc
    {
        public int IDstoc { get; set; }
        public Nullable<int> IDprodus { get; set; }
        public int cantitate { get; set; }
        public string unitate_de_masura { get; set; }
        public System.DateTime data_aprovizionare { get; set; }
        public System.DateTime data_expirare { get; set; }
        public double pret_achizitie { get; set; }
        public double pret_vanzare { get; set; }
        public bool exista { get; set; }
    
        public virtual Produ Produ { get; set; }
    }
}
